### ISSUE TITLE
Extending the module with Plugins

### ISSUE THREAD

**Issue by joaogarin** [drupal-graphql/graphql-search-api#11]
I got a question, maybe you have a better understanding than me at this point about plugins. I want to override a part of our logic on getting facets back to the user in the response. We are indexing term id's in Solr, and as the module just returns whats currently indexed we only get back term id's, thats not terribly useful.

One thing that came to my mind, is overriding (altering) a certain part of the plugin for example in https://github.com/drupal-graphql/graphql-search-api/blob/8.x-1.x/src/Plugin/GraphQL/Fields/SearchAPISearch.php#L326 where I would basically do a taxonomy term load multiple to get the facets information directly from the query. maybe where we would provide a good old alter hook (? is this still a thing?)

Could also possibly do it here possibbly : https://github.com/drupal-graphql/graphql-search-api/blob/8.x-1.x/src/Plugin/GraphQL/Fields/SearchAPIFacetValues.php#L20 where I maybe would override the whole plugin?

this would allow users to extend our plugins and make their own logic..thinking what should be the module's approach to that in a higher level.

**Comment by joaogarin** [comment]
Adding also the tag documentation since this is probably something we would want to make people aware how they can extend the module with their own custom stuff when needed.

**Comment by duartegarin** [comment]
@joaogarin if I understand correctly, you would probably want some custom GraphQL fields that are children of SearchAPIDocument. Those might be specific to terms.

For example imagine you have an indexed field 'job_type' (indexed by tid).
You could also expose something like fieldJobType which is the real Drupal field.

Another option (which is what we do) is to return a custom response that doesn't retrieve fields from Search API but from Drupal itself (we basically don't use the documents at all). We use the SearchAPISearch for the query capacity but then resolve everything in Drupal. This means we only index stuff we need for searches, instead of having to index every field we need in the UI.

I might try to generalise that approach into a feature for GraphQL Search API at some point, but for now I'm doing it with custom fields.

**Comment by duartegarin** [comment]
Also in regards to the tags, I had #7 open for that precise reason, just didn't have time to do it yet.

**Comment by mauforero** [comment]
Hello, @duartegarin. I need to extend the plugin so I can add a geolocation distance filter to a query. Could you please give some advice about how to achieve this?
