### ISSUE TITLE
Expose search_api_relevance score to query

### ISSUE THREAD

**Issue by aubriehill** [drupal-graphql/graphql-search-api#28]
How do I access the `search_api_relevance` score in a query? This is a field that I can expose, filter and sort by in a Drupal view via `search_api` but how can I get this same data in a GraphQL query? 

If it's not currently available, it would be very helpful to be able to use this field for debugging and custom sort purposes. 

Thanks!

**Comment by duartegarin** [comment]
Hi @aubriehill ,
This is not currently supported.
Marking as feature request.
Cheers

**Comment by aubriehill** [comment]
Thanks @duartegarin! Do you have any ideas about how that would be done? Or where the best place for it? Might be something that I can help with!

**Comment by duartegarin** [comment]
Hi @aubriehill ,
Would will need to add a new GraphQL field for this, which can be done via a Plugin.
It's likely that the sort and filter already works if you pass this field, because we are passing the arguments directly to Search API sort and filter functions.
But if you want to access the field itself in the result set you need a new GraphQL field in the schema.

**Comment by aubriehill** [comment]
Thanks for the info @duartegarin! I got it added and made PR with the changes.

**Comment by duartegarin** [comment]
Merged!
